apiVersion: v1
kind: ConfigMap
metadata:
  name: beam-txview-config
  namespace: beam-dev
data:
  config.json: |
    {{json "    " $.TxViewCfg }}
---
apiVersion: v1
kind: Pod
metadata:
  name: beam-txview
  labels:
    beam/app: beam-txview
    beam/type: beam-view
  namespace: beam-dev
  annotations:
    beam/features: "Diagnostics"
spec:
  containers:
  - name: beam-txview
    image: {{$.Images.TxView}}
    args: [ "-cfg", "/etc/beam/config.json" ]
    ports:
    - containerPort: 9980
      name: grpc
    volumeMounts:
    - name: config-volume
      mountPath: /etc/beam
  volumes:
  - name: config-volume
    configMap:
      name: beam-txview-config
